language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_deploy:
  - export RELEASE_ZIP_FILE=$(ls build/distributions/*.zip)
  - echo "deploying $RELEASE_ZIP_FILE to GitHub releases"

jdk:
  - oraclejdk8

script:
  - "./gradlew clean build buildPlugin"

deploy:
  provider: releases
  api_key:
    secure: AAAAB3NzaC1yc2EAAAADAQABAAACAQC4zFiEm2CxZ/GRu60Bo6CyLgujnqkfYU7+ug/4DEYgqpsmR7Erpl9YrrvS8+mUXx2S4nAV93D2ZzPO1+chkBqrlNG96D0y95pbwb/EGY1y5fjkfz/BacJ1ZxoyAuECph9AY7zy0t/OcCRcl63gZ7V6JQ5iIpcrED4njpg4IpBxQSTgCUy+I9UTI4+bmk17OIS2yF3qDOYD76mz2HgiY4IbQDnMCVvMF+v0FlJIhfpqDEKVzEt90/3MpkEYUC9FgtdAOUgsHQ/OsJGS8fhbCO2JEoU7TF/xL2MC6Yyr/GGC78srtSDS47mgqbhjVbg83JoFWxkXFRba8pObytx6jZha/mN+4VjSdAJttsxue4qG23fD+bkGg9zWnbPvtPWo2C/mL3VD/vQkTjEZQBitfI+jhETVe+5ljs2C0xOzNlk6HyVOAn8WTcNIoCNZUIZ/ORh34oBZpWh2h20m8rCFaSUJFXOiULXVMdF5TwIyByQwQmlRbF8ETIJjtCJ0pjV/wIat8bObK5E1Iom1zWGwUYvDzxFTAzz6RmU+3j8a91mxgN1WwGnokiGoYnxdEQadNXVKmQWiyXbqkCBBtTaCJkAohXyGSqXkrNq5kCOV7TGLpo7s2UCgL/YwIC/nA+zUP+gmXBw4azbv6mpPuVvr2sXuoOwwy0UaUk+UYZhLHdTQDw==
  file: "${RELEASE_ZIP_FILE}"
  file_glob: true
  skip_cleanup: true
  on:
    repo: MontiSecArc/intellij_msa_language_plugin
    tags: true
