language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_deploy:
  - export RELEASE_ZIP_FILE=$(ls build/distributions/*.zip)
  - echo "deploying $RELEASE_ZIP_FILE to GitHub releases"

jdk:
  - oraclejdk8

script:
  - "./gradlew clean build buildPlugin"

deploy:
  provider: releases
  api_key:
    secure: veXd2cU/ZP7VKVwdBWBlg+l0FkUXinbvciWO/zCSO9LNKrU3Fcj75zOwjeVwwZwVEpI1u/wAW1N7FI8RD17vQ0vHmLFY1jw6maxo6KnKTWywGwey8ecu9J6TI1/AXUMFQpMlm6J5fRshnGWNFdtyjmfvZYPDRH6UWKV1gl6Aolz1F2VVy1TD4Pqwl7LsXqN//5/duP7lYe2xvjBQoQI4U/grfBaVMDaMy5WrKVrkf0ZejKpg3Z4B13c2wNZYlhBy1H3cSk0/u4kZZ78MmznL7TkFjGAnOi4dZ98in8dtUHkgC/Uez76jj+yp5Q3Fh90z/gKpNm9apGR5uAxmputAHwRxHppMjaG/HH+2NkGOK9e3XRlYcFNf0jN8aVqlwfm3ZKLjZZsOISrfl2uoXCqVm059XWwzWb0kgLX+WAxlSFGokSlpdvy0Eitn59FEb4UjTXU1Rc4ypisYTScIPnRcAV+e0od25xhjOdXApmifcwIjLSSF8VqR+h224AZGpFtsnray4dlIi5B5n3oxcin7c+SobxQNd9qiVpfpUHRIsNUxm3tc9RXOywb3b2kwakoSVg+TjnMikOZhCX09wH8KlSFTcLrX/NEJMvuYSTHkADcWrR/OQ3LKxSLuSPpG0HbQrgWj/nUSCIPuX86ycoChKN8KykAB7zTnEbD9oTL6VLo=
  file: "${RELEASE_ZIP_FILE}"
  file_glob: true
  skip_cleanup: true
  on:
    repo: MontiSecArc/intellij_msa_language_plugin
    tags: true
